# Generated by Django 3.0.6 on 2020-05-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_immage', models.CharField(max_length=200, verbose_name='Имя изображения')),
                ('centerW_immage', models.IntegerField(verbose_name='Середина симметрии по вертикали в пикселях')),
                ('name', models.CharField(max_length=200, verbose_name='Название таблицы')),
                ('folder_column', models.CharField(max_length=200, verbose_name='Имя столбца значенями из которого будут использоваться для создания директории в которую будут сохраняться сгенерированные файлы')),
                ('name_column', models.CharField(max_length=200, verbose_name='Имя столбца значения из которого будут браться для создания генерируемых файлов')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=200, verbose_name='Имя столбца значения из которого будут рисоваться на шаблонном изображении')),
                ('y', models.IntegerField(verbose_name='Отступ от верхнего края изображения')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genDocs.Project')),
            ],
        ),
    ]
