# Generated by Django 3.0.6 on 2020-05-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genDocs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Column',
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'verbose_name': 'Столбец', 'verbose_name_plural': 'Столбцы'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
